### ISSUE TITLE
New Shaped Data - Multiple Groups of Videos

### ISSUE THREAD

**Issue by psenger** [psenger/view-movies#5]
# New Shaped Data - Multiple Groups of Videos

We now have a need to support multiple groups of videos and need to support it.

## As a User:
* login
* I see groups of videos. [mockup](http://imgur.com/a/C81RM)

## Scope: 
This project is to update the UI and the Mock Server only.

## Shape of the data in JSON Schema Format
```JSON
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "items": {
        "properties": {
            "title": {
                "default": "Day One FC Class",
                "description": "A title about the set of videos",
                "title": "The Title Schema",
                "type": "string"
            },
            "videos": { 
                "items": { 
                    "properties": {
                        "title": {
                            "default": "Intro",
                            "description": "An explanation about the video.",
                            "title": "The Video Title",
                            "type": "string"
                        },
                        "url": {
                            "default": "https://www.youtube.com/watch?v=xxxxx",
                            "description": "URL to the video.",
                            "title": "The Url Schema",
                            "type": "string"
                        }
                    },
                    "type": "object"
                },
                "type": "array",
                "uniqueItems": false
            }
        },
        "type": "object"
    },
    "type": "array",
    "uniqueItems": false
}
```
Example:
```json
[
  {
    "title": "Day One FC Class",
    "videos": [
      {
        "title": "Intro",
        "url": "https://www.youtube.com/watch?v=xxxxx"
      },
      {
        "title": "Intro",
        "url": "https://www.youtube.com/watch?v=xxxxx"
      },
      {
        "title": "Intro",
        "url": "https://www.youtube.com/watch?v=xxxxx"
      }
    ]
  },
  {
    "title": "Day Two FC Class",
    "videos": [
      {
        "title": "Intro",
        "url": "https://www.youtube.com/watch?v=xxxxx"
      },
      {
        "title": "Intro",
        "url": "https://www.youtube.com/watch?v=xxxxx"
      }
    ]
  }
]
```
## Tasks
- [ ] Fork the branch
- [ ] download your fork.
- [ ] ```npm install```
- [ ] run the code locally  ```npm run start```
- [ ] update the mock API ```config/webpackDevServer.config.js```
- [ ] test the mock API
- [ ] make a new component in ```src/componets``` that can break down the group of videos
- [ ] make tests for ```src/componets/videoPlayer/videoPlayer.js``` and your new component
- [ ] update ```src/reducer/moviesReducer.js``` add tests
- [ ] update ```src/containers/avaiableVideos/availableVideos.js``` add tests
- [ ] invite me for a code review
- [ ] commit your code to your branch so you can do a pull request.
